# ==================================================================
# Project metadata
# ==================================================================
# Author: Alyssa Bédard
# License: MIT License
# GitHub: https://github.com/alyssabedard/Hanzi2Pinyin
#
# Anki addon that automatically converts Chinese characters (Hanzi)
# to ruby-annotated text with pinyin and zhuyin readings.
#
# Copyright (c) 2025 Alyssa Bédard
# ==================================================================
[project]
name = "Hanzi2Pinyin"
version = "1.0.0"
description = "Anki addon that automatically converts Chinese characters (Hanzi) to ruby-annotated text with pinyin and zhuyin readings."
authors = ["Alyssa Bédard"]
license = "MIT"
homepage = "https://github.com/alyssabedard/Hanzi2Pinyin"

[project.github]
documentation = "https://github.com/alyssabedard/Hanzi2Pinyin"
repository = "https://github.com/alyssabedard/Hanzi2Pinyin"
issues = "https://github.com/alyssabedard/Hanzi2Pinyin/issues"
feature-requests = "https://github.com/alyssabedard/Hanzi2Pinyin/issues"
discussions = "https://github.com/alyssabedard/Hanzi2Pinyin/discussions"

[project.anki]
addon-id = ""
min-version = "23.10"       # Oldest supported Anki version
max-version = "24.12"       # Latest supported Anki version
tested-version = "24.12"    # Manually update this when tested
conflicts = []              # List any conflicting addon IDs
#dependencies = []          # List any required addon ID

[project.maintainers]
primary = "Alyssa Bédard"
contributors = [
    "",
    ""
]

